### ISSUE TITLE
API Request: Covalent

### ISSUE THREAD

**Issue by theericstone** [FlipsideCrypto/livequery-models#19]
## 🚀 API Request

**Describe the new external data source API you're proposing**
Covalent provides APIs that allow users to query transactions, balances, and other key blockchain analytics and stats

**What benefits would this new API bring to you and other users?**
The Covalent API is a fantastic resource but it is purely an API -- connecting their API to the Flipside frontend would be a huge unlock and would augment flipside data with many additional chains (like bitcoin and moonbeam to name a couple)

**Provide an example of how the API might be accessed**
Example via shell
curl --request GET 
     --url https://api.covalenthq.com/v1/{chainName}/address/{walletAddress}/balances_v2/ 
     --header 'accept: application/json' 
     --user 'YOUR_API_KEY:'
     # The colon prevents curl from asking for a password

[there are many other endpoints]

**Additional context**
API docs https://www.covalenthq.com/docs/api/

**Anything else you'd like to add?**
Think it's all there salute-emoji

**Comment by juls858** [comment]
this is live
