### ISSUE TITLE
API Request: Flipside API

### ISSUE THREAD

**Issue by dlrec** [FlipsideCrypto/livequery-models#23]
## 🚀 API Request

**Describe the new external data source API you're proposing**
I propose for the Flipside API to be included in the LiveQuery Approved API's list.

**What benefits would this new API bring to you and other users?**
Reduce the duplication of queries when a user wants to show intermediate results along aggregated data.
A simplified example is shown in the following dashboard:
https://flipsidecrypto.xyz/flyingfish/2023-06-19-05-48-pm-nmiJ7W

**Provide an example of how the API might be accessed**
One option would be to implement something similar to how results are fetched with the SDK.
Ideal and simpler option would be with:
```SQL
SELECT
livequery.live.udf_api('https://api-v2.flipsidecrypto.xyz/{query_id}') as response
```

**Additional context**
In the example dashboard, Query 1 will need to run 2 times (once on it's own and a 2nd time when included in Query 3).
Not knowing the details of engine behind the data app, i think there might be an improvement if Query 3 would only need to fetch the results instead of re-running Query 1 and Query 2.

**Anything else you'd like to add?**
No more details.

**Comment by juls858** [comment]
this is live
