### ISSUE TITLE
Add MarketStack API

### ISSUE THREAD

**Issue by theericstone** [FlipsideCrypto/livequery-models#30]
## 🚀 API Request

**Describe the new external data source API you're proposing**
MarketStack is a JSON API for real-time, intraday and historical stock market data. Users can define multiple stock symbols, retrieve extensive data about 70+ stock exchanges, 170.000+ stock tickers from more than 50 countries, as well as 750+ market indices, information about timezones, currencies, and more. https://marketstack.com/documentation 

**What benefits would this new API bring to you and other users?**
The connection between the stock market and crypto is significant, and will only continue to be moreso with the addition of ETFs and derivatives.

**Provide an example of how the API might be accessed**
https://api.marketstack.com/v1/eod?access_key=YOUR_ACCESS_KEY&symbols = AAPL
pretty straightforward

**Additional context**
No

**Anything else you'd like to add?**
Authentication is required but there is a generous free tier: https://marketstack.com/product

**Comment by juls858** [comment]
this is live
